runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: 'production'
  # ----------------------------------------------------
  # FIX: VITE Build-Time Variables must be passed here
  # These values will be available during the 'npm run build' step on Cloud Build
  # ----------------------------------------------------
  VITE_SUPABASE_URL: 'YOUR_SUPABASE_URL' 
  VITE_SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_KEY' 

handlers:
  # 1. Explicitly serve everything in the 'dist/assets' folder (JS, CSS bundles)
  - url: /assets
    static_dir: dist/assets
    secure: always
    expiration: "7d"
    http_headers:
      Cache-Control: "public, max-age=604800, immutable"

  # 2. Serve specific root-level static files (images, fonts, etc.).
  - url: /(.*\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/(.*\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))$
    secure: always
    expiration: "7d"
    http_headers:
      Cache-Control: "public, max-age=604800, immutable"
      
  # 3. SPA Fallback: All remaining routes (/, /portfolio, /community) go to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
