runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: 'production'

handlers:
  # 1. Explicitly serve all built assets from dist/assets (Vite bundles)
  - url: /assets/(.+)
    static_files: dist/assets/\1
    upload: dist/assets/(.+)
    secure: always
    expiration: "7d"
    http_headers:
      Cache-Control: "public, max-age=604800, immutable"

  # 2. Explicitly serve root-level static files (e.g., LiquidPheonix.png, vite.svg)
  - url: /(.+\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/(.+\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))$
    secure: always
    expiration: "7d"
    http_headers:
      Cache-Control: "public, max-age=604800, immutable"
      
  # 3. SPA Fallback: All other requests route to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
# ... rest of app.yaml

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
